### ISSUE TITLE
[Bug] 1.16.5 无法启动

### ISSUE THREAD

**Issue by MianSoft** [Hendrix-Shen/Tweak-My-Client#13]
### Minecraft Version

1.16.5

### Tweak My Client Version

magiclib-0.5.31.jar

### Description

我自己整了个1.16.5的包，启动器是PCL2，添加该模组之后无法启动游戏。
Fabric是0.14.8 api是0.42.0。

### To Reproduce

100%的无法启动算不算重现（
[1.16.5-Fabric 0.14.8.zip](https://github.com/Hendrix-Shen/Tweak-My-Client/files/8962904/1.16.5-Fabric.0.14.8.zip)

### Expected behavior

我不到啊orz

### Log

[错误报告-2022-6-23_9.10.44.zip](https://github.com/Hendrix-Shen/Tweak-My-Client/files/8962816/-2022-6-23_9.10.44.zip)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by MianSoft** [comment]
我把完整的zip传到了我自己的库里 [1.16.5-Fabric 0.14.8.zip](https://github.com/MianSoft/miansoft.github.io/blob/23349745720b537fc9c2c206a2583b02b9845a37/files/1.16.5-Fabric%200.14.8.zip)

**Comment by Hendrix-Shen** [comment]
你日志上报的是
```
[09:10:35] [main/ERROR]: Error loading companion plugin class [malte0811.ferritecore.mixin.blockstatecache.Config] for mixin config [ferritecore.blockstatecache.mixin.json]. The plugin may be out of date: InvocationTargetException:null
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:97) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:708) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) [fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) [?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at malte0811.ferritecore.mixin.blockstatecache.Config.<init>(Config.java:8) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	... 28 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at malte0811.ferritecore.mixin.config.FerriteConfig$ConfigBuilder.finish(FerriteConfig.java:92) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	at malte0811.ferritecore.mixin.config.FerriteConfig$ConfigBuilder.access$000(FerriteConfig.java:70) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	at malte0811.ferritecore.mixin.config.FerriteConfig.<clinit>(FerriteConfig.java:67) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	at malte0811.ferritecore.mixin.blockstatecache.Config.<init>(Config.java:8) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	... 28 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at malte0811.ferritecore.mixin.config.FerriteConfig$ConfigBuilder.finish(FerriteConfig.java:90) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	at malte0811.ferritecore.mixin.config.FerriteConfig$ConfigBuilder.access$000(FerriteConfig.java:70) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	at malte0811.ferritecore.mixin.config.FerriteConfig.<clinit>(FerriteConfig.java:67) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	at malte0811.ferritecore.mixin.blockstatecache.Config.<init>(Config.java:8) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	... 28 more
Caused by: java.nio.file.NoSuchFileException: config\ferritecore.mixin.properties
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
	at java.nio.file.Files.createFile(Files.java:658) ~[?:?]
	at malte0811.ferritecore.mixin.config.ConfigFileHandler.finish(ConfigFileHandler.java:20) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at malte0811.ferritecore.mixin.config.FerriteConfig$ConfigBuilder.finish(FerriteConfig.java:90) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	at malte0811.ferritecore.mixin.config.FerriteConfig$ConfigBuilder.access$000(FerriteConfig.java:70) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	at malte0811.ferritecore.mixin.config.FerriteConfig.<clinit>(FerriteConfig.java:67) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	at malte0811.ferritecore.mixin.blockstatecache.Config.<init>(Config.java:8) ~[%5B内存优化-铁氧体磁芯%5D%20ferritecore-2.1.0-fabric.jar:?]
	... 28 more
```
你确定是由 TweakMyClient 导致的？

**Comment by MianSoft** [comment]
我把FerriteCore停用后仍然无法启动 orz
[错误报告-2022-6-23_12.57.29.zip](https://github.com/Hendrix-Shen/Tweak-My-Client/files/8963904/-2022-6-23_12.57.29.zip)

**Comment by MianSoft** [comment]
我后台一直开着启动器，日志有点乱，我传了一个新的。
[错误报告-2022-6-23_13.03.27.zip](https://github.com/Hendrix-Shen/Tweak-My-Client/files/8963953/-2022-6-23_13.03.27.zip)

**Comment by MianSoft** [comment]
我把FerriteCore停用后仍然无法启动 orz
[错误报告-2022-6-23_13.10.20.zip](https://github.com/Hendrix-Shen/Tweak-My-Client/files/8964125/-2022-6-23_13.10.20.zip)

**Comment by Hendrix-Shen** [comment]
本喵应该是知道问题的所在了，等下修复。

**Comment by Hendrix-Shen** [comment]
尝试下 [3.1.246+25660ba](https://github.com/Hendrix-Shen/Tweak-My-Client/releases/tag/dev-246) 版本，没处理好单独版本的jar包加载问题，现在应该好了。

**Comment by MianSoft** [comment]
我先抱歉我这几天没有看github忘了这件事，我试了下确实没有bug了，bug修复辛苦了orz
